
CREATE TABLE GSEC_USUARIO
(
	USC_C_USUARIO        NUMBER(10) NOT NULL ,
	USC_D_USUARIO        VARCHAR2(30) NULL ,
	USC_D_PASSWORD       VARCHAR2(100) NULL ,
	USC_D_RESPUESTA      VARCHAR2(100) NULL ,
	USC_E_REGISTRO       NUMBER(1) NULL ,
	USC_C_USUCRE         VARCHAR2(30) NULL ,
	USC_C_USUMOD         VARCHAR2(30) NULL ,
	F_USUARIO_CREA       DATE NULL ,
	IP_TERMINAL_CREA     VARCHAR2(39) NULL ,
	F_USUARIO_MODIFICA   DATE NULL ,
	IP_TERMINAL_MODIFICA VARCHAR2(39) NULL ,
	TRA_C_AREA_DE        NUMBER(10) NULL 
);



CREATE UNIQUE INDEX PK_GSEC_USUARIO ON GSEC_USUARIO
(USC_C_USUARIO   ASC);



ALTER TABLE GSEC_USUARIO
	ADD CONSTRAINT  PK_GSEC_USUARIO PRIMARY KEY (USC_C_USUARIO);



CREATE TABLE TRAC_AREA
(
	TRA_C_AREA_DE        NUMBER(10) NOT NULL ,
	TRA_D_NOMBRE         VARCHAR2(100) NULL 
);



CREATE UNIQUE INDEX PK_TRAC_AREA ON TRAC_AREA
(TRA_C_AREA_DE   ASC);



ALTER TABLE TRAC_AREA
	ADD CONSTRAINT  PK_TRAC_AREA PRIMARY KEY (TRA_C_AREA_DE);



ALTER TABLE GSEC_USUARIO
	ADD (CONSTRAINT R_3 FOREIGN KEY (TRA_C_AREA_DE) REFERENCES TRAC_AREA (TRA_C_AREA_DE) ON DELETE SET NULL);




CREATE SEQUENCE  "TRANSPARENCIA"."SEQ_TRAC_AREA_01"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 656 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  "TRANSPARENCIA"."SEQ_GSEC_USUARIO_02"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 656 NOCACHE  NOORDER  NOCYCLE ;
